### ISSUE TITLE
Image size in Docs > Payments > Integrations > Ecommerce Platforms > Lightspeed > Logging in

### ISSUE THREAD

**Issue by wendyverdonk93** [MultiSafepay/docs#1551]
## Expected Behavior
Images in tab are resized to the size of tab

## Actual Behavior
Images appear to be bigger than tab size. See screenshot.

## Steps to Reproduce the Problem

  1. Open 'logging in' tab on page

## Specifications

  - Url: https://github.com/MultiSafepay/docs/blob/master/content/payments/integrations/ecommerce-platforms/lightspeed_app/faq/logging-in.md
  
  
![tempsnip](https://user-images.githubusercontent.com/85588707/129354085-94bf565d-e742-47cb-b267-3a3704a9daac.jpg)

**Comment by FrancescaNCook** [comment]
@wendyverdonk93  Thanks for reporting. I seem to have changed the dropdown behaviour. But we are planning on reformatting these dropdown as part of the site design overhaul soon anyway.
